defaults:
  - test
  - data

mode: storm            # your runner will call run_storm_experiment(cfg)


test:
  batch_size: 16
  save_raw: true
  save_results: true # This should always be true for an analysis mode.

storm:
  log_same_file:  true   # append to latest testing_info_*.txt
  main_phase:
    start_index: 33
    end_index: 40